language: node_js
node_js:
- "7.4"
branches:
  only:
    - master
    - gh-pages
before_install:
- npm install
script:
- npm run build
- git fetch origin
- git checkout gh-pages
- ls -al
- rm -rf index.html static && cp -r dist/* .
- git status
- git add .
- git commit -m"New build"
- git push
